# Generated by Django 4.2.5 on 2023-10-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagebox',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='box_picture'),
        ),
        migrations.AlterField(
            model_name='storagebox',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='box_picture'),
        ),
        migrations.AlterField(
            model_name='storagebox',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='box_picture'),
        ),
    ]
